# Generated by Django 4.0.7 on 2022-10-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='Pago',
            field=models.FloatField(blank=True, null=True, verbose_name='Pago'),
        ),
    ]
