# Generated by Django 4.1.1 on 2022-09-11 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('IdCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCategoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('IdTipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('NombreTipoUsuario', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IdUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUsuario', models.CharField(max_length=30, verbose_name='Nombre de usuario')),
                ('Descripcion', models.TextField(verbose_name='Descripción')),
                ('NumeroTelefono', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(default='default', max_length=255, unique=True)),
                ('IdTipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.tipousuario', verbose_name='Tipo de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ClasificaEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.categorias', verbose_name='Categoria')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario', verbose_name='Categoria')),
            ],
        ),
    ]
