# Generated by Django 4.0.7 on 2022-10-28 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='Categoria',
        ),
    ]
