# Generated by Django 4.0.7 on 2022-10-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_perfil_intereses_alter_perfil_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='Experiencia',
            field=models.TextField(default='', verbose_name='Intereses'),
        ),
    ]
