# Generated by Django 4.0.7 on 2022-10-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_perfil_experiencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='Descripción',
            new_name='Descripcion',
        ),
    ]
