# Generated by Django 4.0.7 on 2022-10-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_perfil_educacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='NumeroTelefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
