# Generated by Django 4.0.7 on 2022-10-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_alter_perfil_numerotelefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
