# Generated by Django 4.0.7 on 2022-09-26 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPublicacion',
            fields=[
                ('IdCatePub', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCatPub', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('IdPublicacion', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=30, verbose_name='Titulo')),
                ('DescripcionPublicacion', models.TextField(verbose_name='Descripción de la publicación')),
                ('Multimedia', models.BinaryField()),
                ('FechaPublicacion', models.DateField()),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerteneceACategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCatePub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.categoriapublicacion')),
                ('IdPublicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('IdComentario', models.AutoField(primary_key=True, serialize=False)),
                ('Comentario', models.TextField()),
                ('FechaComment', models.DateField()),
                ('IdPublicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacion')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
