# Generated by Django 4.0.7 on 2022-10-23 18:26

import apps.publicaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to=apps.publicaciones.models.user_directory_path)),
            ],
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='Multimedia',
            new_name='Multimedia_Img',
        ),
    ]
