# Generated by Django 4.0.7 on 2022-10-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_video_rename_multimedia_publicacion_multimedia_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='Multimedia_Video',
            field=models.ManyToManyField(blank=True, to='publicaciones.video'),
        ),
    ]
