# Generated by Django 4.0.7 on 2022-10-10 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicaciones', '0002_imagen_comentarios_dislikes_comentarios_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='IdUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_publicacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
