# Generated by Django 4.0.7 on 2022-10-10 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_alter_publicacion_idusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='IdUsuario',
            new_name='Autor',
        ),
    ]
