# Generated by Django 4.0.7 on 2022-10-23 18:53

import apps.publicaciones.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_publicacion_multimedia_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='Multimedia_Video',
            field=models.ManyToManyField(blank=True, to='publicaciones.video', validators=[apps.publicaciones.validators.file_size]),
        ),
    ]
