# Generated by Django 4.1.1 on 2022-09-11 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('IdChat', models.AutoField(primary_key=True, serialize=False)),
                ('NombreChat', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdMensaje', models.IntegerField()),
                ('Mensaje', models.TextField(verbose_name='Mensaje')),
                ('IdChat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat', verbose_name='Chat')),
                ('IdUsuarioEmisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ChateanEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdChat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
            ],
        ),
    ]
